#!/bin/sh -h 

FILE_PATH="/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch"
lockfile="${FILE_PATH}"/lock

FSearch_lock_release() {
   echo "" > /dev/null
}
create_fsearch_db_ctrl() {
    if [ -s "${FILE_PATH}"/fsearch.stat ]; then
        if [ -s "${FILE_PATH}"/fsearch.log ]; then
            echo "ERROR building identifier database failed. Check ${FILE_PATH}/fsearch.log"
        else
            cat "${FILE_PATH}"/fsearch.stat
        fi
        return
    fi
    nohup "$1" > "${FILE_PATH}"/fsearch.log 2>&1 193>/dev/null &
    MY_PID=`echo $!`
    echo "INFO Started building identifier database. Query again once done. Please use VCS elab flag '-genid_db'. (user ${USER}, host ${hostname}, pid ${MY_PID}, ${FILE_PATH}/fsearch.db)"
    echo "INFO Identifier database still building. Query again once done. (user ${USER}, host ${hostname}, pid ${MY_PID}, ${FILE_PATH}/fsearch.db)" > "${FILE_PATH}"/fsearch.stat
    return
}

dir_name=`/usr/bin/dirname "$0"`
if [ "${dir_name}" = "." ]; then
    cd $dir_name
    dir_name=`/bin/pwd`
fi
if [ -d "$dir_name"/../../../../../../../../../../.. ]; then
    cd "$dir_name"/../../../../../../../../../../..
fi

if [ -f "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/.create_fsearch_db" ]; then
    if [ ! -f "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/fsearch.db" ]; then
        if [ "$#" -eq 1 ] && [ "x$1" == "x-background" ]; then
            trap FSearch_lock_release EXIT
            (
                flock 193
                create_fsearch_db_ctrl "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/.create_fsearch_db"
                exit 193
            ) 193> "$lockfile"
            rstat=$?
            if [ "${rstat}"x != "193x" ]; then
                exit $rstat
            fi
        else
            "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/.create_fsearch_db"
        fi
    elif [ -f "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/fsearch.stat" ]; then
       rm -f "/home/zhou/work/arm/AT510-MN-80001-r2p0-00rel0/systems/fpga_testbench/rtl_sim/simv.daidir/debug_dump/fsearch/fsearch.stat"
    fi
fi
